export const initialState = {
  isEditing: false,
  isLoading: false,
  error: null,
  isDialogOpen: false,
  isBulkImportOpen: false,
  selectedEmployee: null,
  showDetailView: false,
  searchTerm: '',
  filterDepartment: 'all',
  isProcessingBulk: false,
  bulkEmployees: [],
  formData: {
    firstName: '',
    lastName: '',
    email: '',
    address: '',
    dateOfBirth: '',
    phoneNumber: '',
    profileImage: '',
    emergencyContact: {
      name: '',
      relationship: '',
      phone: '',
    },
    skills: [],
    education: '',
    experience: '',
    department: '',
    position: '',
    role: 'employee',
    createdAt: '',
    sendInvite: false,
    resetRequested:false,
    startDate: '',
    _id: '',
    middleName: '',
    status: 'active',
    salary:''
  },
  isEditMode: false
};